# https://cmake-format.readthedocs.io/en/latest/
format:
  line_width: 80
  tab_size: 2
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 2
  max_rows_cmdline: 2
  dangle_parens: true
  dangle_align: "prefix"
  min_prefix_chars: 8
  max_prefix_chars: 8
  max_lines_hwrap: 1
  command_case: "lower"
  autosort: True
markup:
  enable_markup: false
